language: python

sudo: false

addons:
  apt:
    packages:
    - xmlsec1

install:
  - pip install -U tox

matrix:
  include:
      - python: 3.4.4
        env: TOXENV=py34
      - python: 3.5
        env: TOXENV=py35

script:
  - tox